### ISSUE TITLE
I have a question, how can i open info window like google map normal when i use this API?

### ISSUE THREAD

**Issue by iaiaia13** [zhenyanghua/MeasureTool-GoogleMaps-V3#4]
I have a question, how can i open info window like google map normal when i use this API ? When i use your API, the mouse always hover and can't open info window anywhere, like bus stop, shop,..

**Comment by zhenyanghua** [comment]
@iaiaia13 Google maps `clickableIcons` option is disabled while measuring because of the `clickableIcons` context has a higher order and it prevents any interception from using Google Maps API. You should still be able to click on `clickableIcons` such as park names (if there they are clickable) after you call `end()` method to complete a measurement.
