### ISSUE TITLE
Option to display total area in Acres rather than miles squared

### ISSUE THREAD

**Issue by codyhoffman** [zhenyanghua/MeasureTool-GoogleMaps-V3#46]
It would be awesome to be able to convert miles squared to acres

**Comment by zhenyanghua** [comment]
Thanks for the PR. It would be, it currently supports only one metric and one imperial on land, and one metric on ocean. With vast unit system many countries and regions they use, with current API, it is unmanageable. This could be an improvement in a new API that allows composition of units. I choose to only include two common measurements to align with what currently Google Maps offers, the additional nautical comes practical when sailing, so I accepted that. With the existing custom API, users can still do the conversion with some efforts without the visual labels. Even though hectare and acre are also commonly used in some land use area, current API structure isn't flexible enough to allow many other regional units to be added as part of the API without messing with the helper class. I am hoping instead of just adding units, a localization feature comes part of it with very simple API to do add-on for units and languages. I don't have a planned date for that milestone yet, but at this moment, I would not like to merge more unit or language specific features into the library so that when the API internally changes, these custom units being dropped will not affect existing users.

**Comment by zhenyanghua** [comment]
#48 This will be part of the new API feature in the v1.0.0 release.
